name: Behavior Drift Application

on: [push]

jobs:
  init:
    name: Initialization

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  drift :
    name: Behavior Drift
    needs: init

    runs-on: ubuntu-latest

    steps:
      - name : Try Behavior Drift
        run: |
          python Behavior_Drift.py

  simulation:
    name: Behavior Modeling
    needs: init

    runs-on: ubuntu-latest

    steps:
      - name: install fbprophet
        run: |
          pip install fbprophet

      - name: Static Modeling - ARUBA
        run: |
          python Behavior_Model -n aruba
